name: Deploy to EKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
        working-directory: ./terraform
        id: terraform

      - name: Install AWS CLI
        run: sudo apt-get install awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-west-2 # or your AWS region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2 # or your AWS region

      - name: Setup Kubeconfig
        run: echo "${{ steps.terraform.outputs.kubeconfig }}" > $GITHUB_WORKSPACE/kubeconfig

      - name: Download kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Deploy to Kubernetes
        run: kubectl apply -f ./k8s/ --kubeconfig $GITHUB_WORKSPACE/kubeconfig
        env:
          KUBECONFIG: $GITHUB_WORKSPACE/kubeconfig
